// temas.js - Banco de dados de Temas Espectrais do ITO
// Padronizado para: 1 = Cenário Ruim / 100 = Cenário Bom

const TEMAS_GENERICOS = [
    "1 = Pior superpoder / 100 = Melhor superpoder",
    "1 = Coisa mais inútil em um apocalipse zumbi / 100 = Mais útil",
    "1 = Filme que você odeia / 100 = Seu filme favorito",
    "1 = Atração turística mais chata / 100 = Atração mais incrível",
    "1 = Profissão menos estressante / 100 = Profissão mais estressante",
    "1 = Pior sabor de sorvete / 100 = Melhor sabor de sorvete",
    "1 = Coisa mais irritante que alguém pode fazer / 100 = Coisa mais fofa",
    "1 = Objeto mais doloroso de pisar descalço / 100 = Objeto mais macio",
    "1 = Pergunta mais idiota / 100 = Pergunta mais inteligente",
    "1 = Pior música para tocar em um casamento / 100 = Melhor música",
    "1 = Presente mais decepcionante / 100 = Presente dos sonhos",
    "1 = Esporte mais entediante de assistir / 100 = Esporte mais emocionante",
    "1 = Pergunta mais difícil de responder / 100 = Pergunta mais fácil",
    "1 = Coisa mais nojenta / 100 = Coisa mais deliciosa",
    "1 = Pior lugar para ir num primeiro encontro / 100 = Melhor lugar",
    "1 = Banda ou artista que você detesta / 100 = Sua banda/artista favorita",
    "1 = Hábito mais irritante em um colega de quarto / 100 = Melhor hábito",
    "1 = Coisa mais brega / 100 = Coisa mais chique",
    "1 = Pior desculpa para chegar atrasado / 100 = Desculpa mais criativa",
    "1 = Videogame mais difícil / 100 = Videogame mais fácil",
    "1 = Pior cheiro do mundo / 100 = Melhor cheiro do mundo",
    "1 = Coisa mais assustadora / 100 = Coisa mais inofensiva",
    "1 = Item mais inútil que você possui / 100 = Item mais essencial",
    "1 = Pior filme da Disney / 100 = Melhor filme da Disney",
    "1 = Habilidade mais difícil de aprender / 100 = Habilidade mais fácil",
    "1 = Coisa mais difícil de cozinhar / 100 = Coisa mais fácil",
    "1 = Animal mais perigoso / 100 = Animal mais fofo",
    "1 = Pior programa de TV / 100 = Melhor programa de TV",
    "1 = Coisa mais viciante / 100 = Coisa que você enjoa rápido",
    "1 = Assunto mais chato de estudar / 100 = Assunto mais interessante",
    "1 = Pior aplicativo do seu celular / 100 = Aplicativo mais útil",
    "1 = Coisa mais difícil de perdoar / 100 = Coisa mais fácil",
    "1 = Pior sabor de pizza / 100 = Melhor sabor de pizza",
    "1 = Coisa mais ridícula que alguém pode usar / 100 = Coisa mais estilosa",
    "1 = Brinquedo mais perigoso / 100 = Brinquedo mais seguro",
    "1 = Livro mais chato que você já leu / 100 = Melhor livro",
    "1 = Pior lugar para ficar preso / 100 = Melhor lugar para ficar preso",
    "1 = Coisa mais difícil de dizer a alguém / 100 = Coisa mais fácil",
    "1 = Pior cobertura de bolo / 100 = Melhor cobertura de bolo",
    "1 = Atividade mais cansativa / 100 = Atividade mais relaxante",
    "1 = Coisa mais difícil de consertar / 100 = Coisa mais fácil",
    "1 = Animal mais inútil / 100 = Animal mais útil",
    "1 = Pior tipo de clima / 100 = Melhor tipo de clima",
    "1 = Coisa mais brega dos anos 90 / 100 = Coisa mais legal",
    "1 = Jogo de tabuleiro mais confuso / 100 = Jogo mais simples",
    "1 = Pior corte de cabelo / 100 = Melhor corte de cabelo",
    "1 = Coisa mais difícil de economizar dinheiro / 100 = Coisa mais fácil",
    "1 = Pior tipo de queijo / 100 = Melhor tipo de queijo",
    "1 = Atividade mais perigosa / 100 = Atividade mais segura",
    "1 = Pior música dos anos 80 / 100 = Melhor música dos anos 80",
    "1 = Coisa mais difícil de manter limpa / 100 = Coisa mais fácil",
    "1 = Pior sabor de refrigerante / 100 = Melhor sabor de refrigerante",
    "1 = Hábito mais difícil de quebrar / 100 = Habilidade mais fácil de aprender",
    "1 = Pior lugar para trabalhar / 100 = Melhor lugar para trabalhar",
    "1 = Coisa mais difícil de fazer com as mãos / 100 = Coisa mais fácil",
    "1 = Pior supervilão / 100 = Melhor supervilão",
    "1 = Coisa mais irritante na internet / 100 = Coisa mais legal",
    "1 = Pior tipo de exercício físico / 100 = Melhor tipo de exercício",
    "1 = Coisa mais difícil de desenhar / 100 = Coisa mais fácil",
    "1 = Pior sabor de chiclete / 100 = Melhor sabor de chiclete",
    "1 = Atividade mais solitária / 100 = Atividade mais social",
    "1 = Coisa mais difícil de dobrar / 100 = Coisa mais fácil",
    "1 = Pior tipo de calçado / 100 = Melhor tipo de calçado",
    "1 = Coisa mais brega de decoração / 100 = Coisa mais estilosa",
    "1 = Pior programa de rádio / 100 = Melhor programa de rádio",
    "1 = Coisa mais difícil de explicar a uma criança / 100 = Coisa mais fácil",
    "1 = Pior sabor de suco / 100 = Melhor sabor de suco",
    "1 = Coisa mais difícil de encontrar / 100 = Coisa mais fácil",
    "1 = Pior tipo de transporte / 100 = Melhor tipo de transporte",
    "1 = Coisa mais brega de roupa / 100 = Coisa mais legal",
    "1 = Pior jogo de cartas / 100 = Melhor jogo de cartas",
    "1 = Coisa mais difícil de carregar / 100 = Coisa mais fácil",
    "1 = Pior sabor de iogurte / 100 = Melhor sabor de iogurte",
    "1 = Coisa mais difícil de engolir / 100 = Coisa mais fácil",
    "1 = Pior tipo de travesseiro / 100 = Melhor tipo de travesseiro",
    "1 = Coisa mais brega de casamento / 100 = Coisa mais legal",
    "1 = Pior sabor de chá / 100 = Melhor sabor de chá",
    "1 = Coisa mais difícil de abrir / 100 = Coisa mais fácil",
    "1 = Pior tipo de cadeira / 100 = Melhor tipo de cadeira",
    "1 = Pior sabor de batata frita / 100 = Melhor sabor de batata frita",
    "1 = Coisa mais difícil de montar / 100 = Coisa mais fácil",
    "1 = Pior sabor de bolacha / 100 = Melhor sabor de bolacha",
    "1 = Pior sabor de chocolate / 100 = Melhor sabor de chocolate",
    "1 = Pior tipo de colchão / 100 = Melhor tipo de colchão",
    "1 = Pior sabor de sopa / 100 = Melhor sabor de sopa",
    "1 = Pior sabor de molho / 100 = Melhor sabor de molho",
];

const TEMAS_GENERICOS_EN = [
    "1 = Worst superpower / 100 = Best superpower",
    "1 = Most useless thing in a zombie apocalypse / 100 = Most useful",
    "1 = Movie you hate / 100 = Your favorite movie",
    "1 = Most boring tourist attraction / 100 = Most amazing attraction",
    "1 = Least stressful job / 100 = Most stressful job",
    "1 = Worst ice cream flavor / 100 = Best ice cream flavor",
    "1 = Most annoying thing someone can do / 100 = Cutest thing",
    "1 = Most painful object to step on barefoot / 100 = Softest object",
    "1 = Dumbest question / 100 = Smartest question",
    "1 = Worst song to play at a wedding / 100 = Best song",
    "1 = Most disappointing gift / 100 = Dream gift",
    "1 = Most boring sport to watch / 100 = Most exciting sport",
    "1 = Hardest question to answer / 100 = Easiest question",
    "1 = Most disgusting thing / 100 = Most delicious thing",
    "1 = Worst place for a first date / 100 = Best place",
    "1 = Band or artist you hate / 100 = Your favorite band/artist",
    "1 = Most annoying roommate habit / 100 = Best habit",
    "1 = Cheesiest thing / 100 = Most stylish thing",
    "1 = Worst excuse for being late / 100 = Most creative excuse",
    "1 = Hardest video game / 100 = Easiest video game",
    "1 = Worst smell in the world / 100 = Best smell in the world",
    "1 = Scariest thing / 100 = Most harmless thing",
    "1 = Most useless item you own / 100 = Most essential item",
    "1 = Worst Disney movie / 100 = Best Disney movie",
    "1 = Hardest skill to learn / 100 = Easiest skill",
    "1 = Hardest thing to cook / 100 = Easiest thing to cook",
    "1 = Most dangerous animal / 100 = Cutest animal",
    "1 = Worst TV show / 100 = Best TV show",
    "1 = Most addictive thing / 100 = Thing you get tired of fastest",
    "1 = Most boring subject to study / 100 = Most interesting subject",
    "1 = Worst app on your phone / 100 = Most useful app",
    "1 = Hardest thing to forgive / 100 = Easiest thing to forgive",
    "1 = Worst pizza topping / 100 = Best pizza topping",
    "1 = Most ridiculous thing to wear / 100 = Most stylish thing",
    "1 = Most dangerous toy / 100 = Safest toy",
    "1 = Most boring book you've read / 100 = Best book",
    "1 = Worst place to be stuck / 100 = Best place to be stuck",
    "1 = Hardest thing to say to someone / 100 = Easiest thing",
    "1 = Worst cake topping / 100 = Best cake topping",
    "1 = Most tiring activity / 100 = Most relaxing activity",
    "1 = Most useless animal / 100 = Most useful animal",
    "1 = Worst type of weather / 100 = Best type of weather",
    "1 = Cheesiest 90s thing / 100 = Coolest 90s thing",
    "1 = Most confusing board game / 100 = Simplest board game",
    "1 = Worst haircut / 100 = Best haircut",
    "1 = Worst type of cheese / 100 = Best type of cheese",
    "1 = Most dangerous activity / 100 = Safest activity",
    "1 = Worst 80s song / 100 = Best 80s song",
    "1 = Worst soda flavor / 100 = Best soda flavor",
    "1 = Worst place to work / 100 = Best place to work",
    "1 = Worst villain / 100 = Best villain",
    "1 = Most annoying thing on the internet / 100 = Coolest thing",
    "1 = Worst type of exercise / 100 = Best type of exercise",
    "1 = Hardest thing to draw / 100 = Easiest thing to draw",
    "1 = Worst gum flavor / 100 = Best gum flavor",
    "1 = Most solitary activity / 100 = Most social activity",
    "1 = Worst footwear / 100 = Best footwear",
    "1 = Worst thing to explain to a child / 100 = Easiest thing",
    "1 = Worst type of transport / 100 = Best type of transport",
    "1 = Worst card game / 100 = Best card game",
    "1 = Worst yogurt flavor / 100 = Best yogurt flavor",
    "1 = Worst pillow / 100 = Best pillow",
    "1 = Worst tea flavor / 100 = Best tea flavor",
    "1 = Worst type of chair / 100 = Best type of chair",
    "1 = Worst chip flavor / 100 = Best chip flavor",
    "1 = Worst chocolate flavor / 100 = Best chocolate flavor",
    "1 = Worst mattress / 100 = Best mattress",
    "1 = Worst soup flavor / 100 = Best soup flavor",
    "1 = Worst sauce / 100 = Best sauce",
    "1 = Hardest habit to break / 100 = Easiest skill to learn",
    "1 = Worst thing to carry / 100 = Easiest thing to carry",
];

const TEMAS_GENERICOS_ES = [
    "1 = Peor superpoder / 100 = Mejor superpoder",
    "1 = Cosa más inútil en un apocalipsis zombie / 100 = Más útil",
    "1 = Película que odias / 100 = Tu película favorita",
    "1 = Atracción turística más aburrida / 100 = Atracción más increíble",
    "1 = Trabajo menos estresante / 100 = Trabajo más estresante",
    "1 = Peor sabor de helado / 100 = Mejor sabor de helado",
    "1 = Cosa más irritante que alguien puede hacer / 100 = Cosa más tierna",
    "1 = Objeto más doloroso en el que pisar descalzo / 100 = Objeto más suave",
    "1 = Pregunta más tonta / 100 = Pregunta más inteligente",
    "1 = Peor canción para una boda / 100 = Mejor canción",
    "1 = Regalo más decepcionante / 100 = Regalo de tus sueños",
    "1 = Deporte más aburrido de ver / 100 = Deporte más emocionante",
    "1 = Pregunta más difícil de responder / 100 = Pregunta más fácil",
    "1 = Cosa más asquerosa / 100 = Cosa más deliciosa",
    "1 = Peor lugar para una primera cita / 100 = Mejor lugar",
    "1 = Banda o artista que detestas / 100 = Tu banda/artista favorita",
    "1 = Hábito más irritante de un compañero de cuarto / 100 = Mejor hábito",
    "1 = Cosa más cursi / 100 = Cosa más elegante",
    "1 = Peor excusa para llegar tarde / 100 = Excusa más creativa",
    "1 = Videojuego más difícil / 100 = Videojuego más fácil",
    "1 = Peor olor del mundo / 100 = Mejor olor del mundo",
    "1 = Cosa más aterradora / 100 = Cosa más inofensiva",
    "1 = Objeto más inútil que tienes / 100 = Objeto más esencial",
    "1 = Peor película de Disney / 100 = Mejor película de Disney",
    "1 = Habilidad más difícil de aprender / 100 = Más fácil de aprender",
    "1 = Cosa más difícil de cocinar / 100 = Cosa más fácil",
    "1 = Animal más peligroso / 100 = Animal más tierno",
    "1 = Peor programa de TV / 100 = Mejor programa de TV",
    "1 = Cosa más adictiva / 100 = Cosa de la que te cansas más rápido",
    "1 = Materia más aburrida de estudiar / 100 = Materia más interesante",
    "1 = Peor aplicación de tu celular / 100 = Aplicación más útil",
    "1 = Cosa más difícil de perdonar / 100 = Cosa más fácil",
    "1 = Peor sabor de pizza / 100 = Mejor sabor de pizza",
    "1 = Cosa más ridícula que alguien puede ponerse / 100 = Cosa más estilosa",
    "1 = Juguete más peligroso / 100 = Juguete más seguro",
    "1 = Libro más aburrido que has leído / 100 = Mejor libro",
    "1 = Peor lugar para quedarse atrapado / 100 = Mejor lugar",
    "1 = Cosa más difícil de decirle a alguien / 100 = Cosa más fácil",
    "1 = Peor cobertura de pastel / 100 = Mejor cobertura de pastel",
    "1 = Actividad más agotadora / 100 = Actividad más relajante",
    "1 = Animal más inútil / 100 = Animal más útil",
    "1 = Peor tipo de clima / 100 = Mejor tipo de clima",
    "1 = Cosa más cursi de los 90 / 100 = Cosa más genial",
    "1 = Juego de mesa más confuso / 100 = Juego más simple",
    "1 = Peor corte de pelo / 100 = Mejor corte de pelo",
    "1 = Peor tipo de queso / 100 = Mejor tipo de queso",
    "1 = Actividad más peligrosa / 100 = Actividad más segura",
    "1 = Peor canción de los 80 / 100 = Mejor canción de los 80",
    "1 = Peor sabor de refresco / 100 = Mejor sabor de refresco",
    "1 = Peor lugar para trabajar / 100 = Mejor lugar para trabajar",
    "1 = Peor villano / 100 = Mejor villano",
    "1 = Cosa más irritante de internet / 100 = Cosa más genial",
    "1 = Peor tipo de ejercicio / 100 = Mejor tipo de ejercicio",
    "1 = Cosa más difícil de dibujar / 100 = Cosa más fácil",
    "1 = Peor sabor de chicle / 100 = Mejor sabor de chicle",
    "1 = Actividad más solitaria / 100 = Actividad más social",
    "1 = Peor calzado / 100 = Mejor calzado",
    "1 = Cosa más difícil de explicarle a un niño / 100 = Cosa más fácil",
    "1 = Peor tipo de transporte / 100 = Mejor tipo de transporte",
    "1 = Peor juego de cartas / 100 = Mejor juego de cartas",
    "1 = Peor sabor de yogur / 100 = Mejor sabor de yogur",
    "1 = Peor almohada / 100 = Mejor almohada",
    "1 = Peor sabor de té / 100 = Mejor sabor de té",
    "1 = Peor tipo de silla / 100 = Mejor tipo de silla",
    "1 = Peor sabor de papas fritas / 100 = Mejor sabor",
    "1 = Peor sabor de chocolate / 100 = Mejor sabor de chocolate",
    "1 = Peor colchón / 100 = Mejor colchón",
    "1 = Peor sabor de sopa / 100 = Mejor sabor de sopa",
    "1 = Peor salsa / 100 = Mejor salsa",
    "1 = Hábito más difícil de romper / 100 = Habilidad más fácil de aprender",
    "1 = Cosa más difícil de cargar / 100 = Cosa más fácil de cargar",
];
