// temas.js - Banco de dados de Temas Espectrais do ITO
// Padronizado para: 1 = Cenário Ruim / 100 = Cenário Bom

const TEMAS_GENERICOS = [
    "1 = Pior superpoder / 100 = Melhor superpoder",
    "1 = Coisa mais inútil em um apocalipse zumbi / 100 = Mais útil",
    "1 = Filme que você odeia / 100 = Seu filme favorito",
    "1 = Atração turística mais chata / 100 = Atração mais incrível",
    "1 = Profissão menos estressante / 100 = Profissão mais estressante",
    "1 = Pior sabor de sorvete / 100 = Melhor sabor de sorvete",
    "1 = Coisa mais irritante que alguém pode fazer / 100 = Coisa mais fofa",
    "1 = Objeto mais doloroso de pisar descalço / 100 = Objeto mais macio",
    "1 = Pergunta mais idiota / 100 = Pergunta mais inteligente",
    "1 = Pior música para tocar em um casamento / 100 = Melhor música",
    "1 = Presente mais decepcionante / 100 = Presente dos sonhos",
    "1 = Esporte mais entediante de assistir / 100 = Esporte mais emocionante",
    "1 = Pergunta mais difícil de responder / 100 = Pergunta mais fácil",
    "1 = Coisa mais nojenta / 100 = Coisa mais deliciosa",
    "1 = Pior lugar para ir num primeiro encontro / 100 = Melhor lugar",
    "1 = Banda ou artista que você detesta / 100 = Sua banda/artista favorita",
    "1 = Hábito mais irritante em um colega de quarto / 100 = Melhor hábito",
    "1 = Coisa mais brega / 100 = Coisa mais chique",
    "1 = Pior desculpa para chegar atrasado / 100 = Desculpa mais criativa",
    "1 = Videogame mais difícil / 100 = Videogame mais fácil",
    "1 = Pior cheiro do mundo / 100 = Melhor cheiro do mundo",
    "1 = Coisa mais assustadora / 100 = Coisa mais inofensiva",
    "1 = Item mais inútil que você possui / 100 = Item mais essencial",
    "1 = Pior filme da Disney / 100 = Melhor filme da Disney",
    "1 = Habilidade mais difícil de aprender / 100 = Habilidade mais fácil",
    "1 = Coisa mais difícil de cozinhar / 100 = Coisa mais fácil",
    "1 = Animal mais perigoso / 100 = Animal mais fofo",
    "1 = Pior programa de TV / 100 = Melhor programa de TV",
    "1 = Coisa mais viciante / 100 = Coisa que você enjoa rápido",
    "1 = Assunto mais chato de estudar / 100 = Assunto mais interessante",
    "1 = Pior aplicativo do seu celular / 100 = Aplicativo mais útil",
    "1 = Coisa mais difícil de perdoar / 100 = Coisa mais fácil",
    "1 = Pior sabor de pizza / 100 = Melhor sabor de pizza",
    "1 = Coisa mais ridícula que alguém pode usar / 100 = Coisa mais estilosa",
    "1 = Brinquedo mais perigoso / 100 = Brinquedo mais seguro",
    "1 = Livro mais chato que você já leu / 100 = Melhor livro",
    "1 = Pior lugar para ficar preso / 100 = Melhor lugar para ficar preso",
    "1 = Coisa mais difícil de dizer a alguém / 100 = Coisa mais fácil",
    "1 = Pior cobertura de bolo / 100 = Melhor cobertura de bolo",
    "1 = Atividade mais cansativa / 100 = Atividade mais relaxante",
    "1 = Coisa mais difícil de consertar / 100 = Coisa mais fácil",
    "1 = Animal mais inútil / 100 = Animal mais útil",
    "1 = Pior tipo de clima / 100 = Melhor tipo de clima",
    "1 = Coisa mais brega dos anos 90 / 100 = Coisa mais legal",
    "1 = Jogo de tabuleiro mais confuso / 100 = Jogo mais simples",
    "1 = Pior corte de cabelo / 100 = Melhor corte de cabelo",
    "1 = Coisa mais difícil de economizar dinheiro / 100 = Coisa mais fácil",
    "1 = Pior tipo de queijo / 100 = Melhor tipo de queijo",
    "1 = Atividade mais perigosa / 100 = Atividade mais segura",
    "1 = Pior música dos anos 80 / 100 = Melhor música dos anos 80",
    "1 = Coisa mais difícil de manter limpa / 100 = Coisa mais fácil",
    "1 = Pior sabor de refrigerante / 100 = Melhor sabor de refrigerante",
    "1 = Hábito mais difícil de quebrar / 100 = Habilidade mais fácil de aprender",
    "1 = Pior lugar para trabalhar / 100 = Melhor lugar para trabalhar",
    "1 = Coisa mais difícil de fazer com as mãos / 100 = Coisa mais fácil",
    "1 = Pior supervilão / 100 = Melhor supervilão",
    "1 = Coisa mais irritante na internet / 100 = Coisa mais legal",
    "1 = Pior tipo de exercício físico / 100 = Melhor tipo de exercício",
    "1 = Coisa mais difícil de desenhar / 100 = Coisa mais fácil",
    "1 = Pior sabor de chiclete / 100 = Melhor sabor de chiclete",
    "1 = Atividade mais solitária / 100 = Atividade mais social",
    "1 = Coisa mais difícil de dobrar / 100 = Coisa mais fácil",
    "1 = Pior tipo de calçado / 100 = Melhor tipo de calçado",
    "1 = Coisa mais brega de decoração / 100 = Coisa mais estilosa",
    "1 = Pior programa de rádio / 100 = Melhor programa de rádio",
    "1 = Coisa mais difícil de explicar a uma criança / 100 = Coisa mais fácil",
    "1 = Pior sabor de suco / 100 = Melhor sabor de suco",
    "1 = Coisa mais difícil de encontrar / 100 = Coisa mais fácil",
    "1 = Pior tipo de transporte / 100 = Melhor tipo de transporte",
    "1 = Coisa mais brega de roupa / 100 = Coisa mais legal",
    "1 = Pior jogo de cartas / 100 = Melhor jogo de cartas",
    "1 = Coisa mais difícil de carregar / 100 = Coisa mais fácil",
    "1 = Pior tipo de areia / 100 = Melhor tipo de areia",
    "1 = Coisa mais difícil de engolir / 100 = Coisa mais fácil",
    "1 = Pior sabor de iogurte / 100 = Melhor sabor de iogurte",
    "1 = Coisa mais difícil de jogar / 100 = Coisa mais fácil",
    "1 = Pior tipo de travesseiro / 100 = Melhor tipo de travesseiro",
    "1 = Coisa mais brega de casamento / 100 = Coisa mais legal",
    "1 = Pior sabor de chá / 100 = Melhor sabor de chá",
    "1 = Coisa mais difícil de abrir / 100 = Coisa mais fácil",
    "1 = Pior tipo de cadeira / 100 = Melhor tipo de cadeira",
    "1 = Coisa mais difícil de fechar / 100 = Coisa mais fácil",
    "1 = Pior sabor de batata frita / 100 = Melhor sabor de batata frita",
    "1 = Coisa mais difícil de montar / 100 = Coisa mais fácil",
    "1 = Pior tipo de caneta / 100 = Melhor tipo de caneta",
    "1 = Coisa mais difícil de limpar / 100 = Coisa mais fácil",
    "1 = Pior sabor de bolacha / 100 = Melhor sabor de bolacha",
    "1 = Coisa mais difícil de segurar / 100 = Coisa mais fácil",
    "1 = Pior tipo de toalha / 100 = Melhor tipo de toalha",
    "1 = Coisa mais difícil de usar / 100 = Coisa mais fácil",
    "1 = Pior sabor de chocolate / 100 = Melhor sabor de chocolate",
    "1 = Coisa mais difícil de ler / 100 = Coisa mais fácil",
    "1 = Pior tipo de colchão / 100 = Melhor tipo de colchão",
    "1 = Coisa mais difícil de escrever / 100 = Coisa mais fácil",
    "1 = Pior sabor de sopa / 100 = Melhor sabor de sopa",
    "1 = Coisa mais difícil de ouvir / 100 = Coisa mais fácil",
    "1 = Pior tipo de luz / 100 = Melhor tipo de luz",
    "1 = Coisa mais difícil de ver / 100 = Coisa mais fácil",
    "1 = Pior sabor de molho / 100 = Melhor sabor de molho",
    "1 = Coisa mais difícil de cheirar / 100 = Coisa mais fácil"
];